version: '2'

services:
  crawler:
    container_name: crawler
    build: ./app
    env_file: .env
    ports:
      - "6800:6800"
    networks:
      - default
      - eap_default
    volumes:
      - ./app:/usr/src/app

networks:
  eap_default:
    external: True
